defaults: &defaults
  adapter: postgresql
  pool: 5
  username: pgsql 
  password: miller
  timeout: 5000

development:
  <<: *defaults
  database: mycrm_development

test:
  <<: *defaults
  database: mycrm_test

production:
  <<: *defaults
  database: mycrm_production
